### ISSUE TITLE
create task list

### ISSUE THREAD

**Issue by Archchaya** [Archchaya/markdown-portfolio#2]
- [ ] Outline my portfolio
- [ ] Introduce myself to the world

**Comment by Archchaya** [comment]
- [ ] Outline my portfolio
- [ ] Introduce myself to the world
